# Lab 1.4: device-cluster baseline with replication-factor 3 only
# Mirrors manifests/disk-replication-factor-rf3.yaml / helm/disk-cluster-values.yaml
replicas: 3
enableDynamicConfigUpdate: true

image:
  repository: aerospike/aerospike-server-enterprise
  tag: "8.1.0.0"

podSpec:
  nodeSelector:
    workshop.aerospike.com/node-pool: baseline
  multiPodPerHost: false
  aerospikeContainer:
    resources:
      requests:
        cpu: "7"
        memory: 57Gi
      limits:
        cpu: "7"
        memory: 57Gi
  sidecars:
    - name: aerospike-prometheus-exporter
      image: aerospike/aerospike-prometheus-exporter:1.33.0
      ports:
        - containerPort: 9145
          name: exporter
      env:
        - name: AS_AUTH_USER
          value: exporter
        - name: AS_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: auth-exporter-secret
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi


storage:
  localStorageClasses:
    - local-ssd
  filesystemVolumePolicy:
    cascadeDelete: true
    initMethod: deleteFiles
  blockVolumePolicy:
    cascadeDelete: true
    initMethod: blkdiscardWithHeaderCleanup
    wipeMethod: blkdiscard
  volumes:
    - name: workdir
      source:
        persistentVolume:
          storageClass: ssd
          volumeMode: Filesystem
          size: 3Gi
      aerospike:
        path: /opt/aerospike
    - name: ns
      source:
        persistentVolume:
          storageClass: local-ssd
          volumeMode: Block
          accessModes: ["ReadWriteOnce"]
          size: 250Gi
      aerospike:
        path: /dev/data/local1
    - name: aerospike-config-secret
      source:
        secret:
          secretName: aerospike-secret
      aerospike:
        path: /etc/aerospike/secret

aerospikeAccessControl:
  users:
    - name: admin
      secretName: auth-secret
      roles:
        - sys-admin
        - user-admin
    - name: app
      secretName: auth-app-secret
      roles:
        - read
        - write
    - name: exporter
      secretName: auth-exporter-secret
      roles: []


aerospikeConfig:
  service:
    feature-key-file: /etc/aerospike/secret/features.conf
  security: {}
  network:
    service:
      port: 3000
    fabric:
      port: 3001
    heartbeat:
      port: 3002
    admin:
      port: 3003
  namespaces:
    - name: test
      replication-factor: 3
      migrate-sleep: 0 # For demo purposes only
      indexes-memory-budget: 49478021959  # 80% of 57.6 GiB (90% of 64 GiB) = 46.08 GiB
      storage-engine:
        type: device
        devices:
          - /dev/data/local1